FROM nvcr.io/nvidia/pytorch:24.01-py3

LABEL maintainer="alain.keller@ost.ch"

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install ffmpeg libsm6 libxext6 xvfb -y

RUN python3 -m pip install --user --upgrade pip
RUN pip3 install --user \
	tensorboard \
	matplotlib \
	tqdm \
	ipdb \
	black \
	timm==0.5.4 \
  'gymnasium[mujoco]' \
  gymnasium==1.0.0a1 \
  opencv-python
#	opencv-python
# RUN pip3 install --user \
	# pycuda
